import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

export default function Dashboard() {
  return (
    <div>
      <Navbar />

      <main className="min-h-screen bg-gray-100 p-10">
        <h1 className="text-5xl font-bold text-center text-green-700 mb-10">
          Farmer Dashboard 🌾
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

          <div className="bg-white p-6 rounded-xl shadow-lg">
            <h2 className="text-2xl font-bold mb-3">💬 Previous Chats</h2>
            <p>Access all your previous AI conversations.</p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-lg">
            <h2 className="text-2xl font-bold mb-3">📋 Disease Reports</h2>
            <p>View crop disease analysis reports generated by AI.</p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-lg">
            <h2 className="text-2xl font-bold mb-3">🌱 Recommendations</h2>
            <p>Explore personalized farming recommendations.</p>
          </div>

        </div>
      </main>

      <Footer />
    </div>
  );
}