// import Navbar from "../../components/Navbar";
// import Footer from "../../components/Footer";

// export default function Dashboard() {
//   return (
//     <div>
//       <Navbar />

//       <main className="min-h-screen bg-gray-100 p-10">
//         <h1 className="text-5xl font-bold text-center text-green-700 mb-10">
//           Farmer Dashboard 🌾
//         </h1>

//         <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

//           <div className="bg-white p-6 rounded-xl shadow-lg">
//             <h2 className="text-2xl font-bold mb-3">💬 Previous Chats</h2>
//             <p>Access all your previous AI conversations.</p>
//           </div>

//           <div className="bg-white p-6 rounded-xl shadow-lg">
//             <h2 className="text-2xl font-bold mb-3">📋 Disease Reports</h2>
//             <p>View crop disease analysis reports generated by AI.</p>
//           </div>

//           <div className="bg-white p-6 rounded-xl shadow-lg">
//             <h2 className="text-2xl font-bold mb-3">🌱 Recommendations</h2>
//             <p>Explore personalized farming recommendations.</p>
//           </div>

//         </div>
//       </main>

//       <Footer />
//     </div>
//   );
// }
// import Navbar from "../../components/Navbar";
// import Footer from "../../components/Footer";

// export default function Dashboard() {
//   return (
//     <div>
//       <Navbar />

//       <main className="min-h-screen bg-gray-100 p-10">

//         {/* HERO / ABOUT SECTION */}
//         <div className="bg-gradient-to-r from-green-600 to-green-400 text-white p-8 rounded-2xl shadow-lg mb-10">
//           <h2 className="text-3xl font-bold mb-3">Welcome to AIgri 🌾</h2>
//           <p className="text-lg opacity-90 max-w-3xl">
//             AIgri helps farmers make smarter decisions using AI-powered crop analysis,
//             disease detection, and personalized recommendations. Upload crop images,
//             chat with AI, and get instant agricultural insights — all in one place.
//           </p>

//           <div className="mt-5 flex gap-3 flex-wrap">
//             <span className="bg-white/20 px-3 py-1 rounded-full text-sm">🌱 Crop Intelligence</span>
//             <span className="bg-white/20 px-3 py-1 rounded-full text-sm">📊 AI Reports</span>
//             <span className="bg-white/20 px-3 py-1 rounded-full text-sm">💬 Smart Chat</span>
//             <span className="bg-white/20 px-3 py-1 rounded-full text-sm">🌾 Farming Insights</span>
//           </div>
//         </div>

//         {/* STATS SECTION */}
//         <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-10 text-center">
//           <div className="bg-white rounded-xl p-5 shadow">
//             <h3 className="text-2xl font-bold text-green-700">AI Powered</h3>
//             <p className="text-gray-500 text-sm mt-1">
//               Smart agricultural insights for better farming decisions
//             </p>
//           </div>

//           <div className="bg-white rounded-xl p-5 shadow">
//             <h3 className="text-2xl font-bold text-green-700">Real-Time</h3>
//             <p className="text-gray-500 text-sm mt-1">
//               Instant crop disease detection and recommendations
//             </p>
//           </div>

//           <div className="bg-white rounded-xl p-5 shadow">
//             <h3 className="text-2xl font-bold text-green-700">Personalized</h3>
//             <p className="text-gray-500 text-sm mt-1">
//               Tailored advice based on your farm conditions
//             </p>
//           </div>
//         </div>

//         {/* TITLE */}
//         <h1 className="text-4xl font-bold text-center text-green-700 mb-10">
//           Farmer Dashboard 🌾
//         </h1>

//         {/* CARDS */}
//         <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

//           <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-2xl transition">
//             <h2 className="text-2xl font-bold mb-3">💬 Previous Chats</h2>
//             <p className="text-gray-600">
//               Revisit past AI conversations to track your farming decisions and insights over time.
//             </p>
//           </div>

//           <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-2xl transition">
//             <h2 className="text-2xl font-bold mb-3">📋 Disease Reports</h2>
//             <p className="text-gray-600">
//               Get AI-generated analysis of crop diseases with possible treatments and prevention tips.
//             </p>
//           </div>

//           <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-2xl transition">
//             <h2 className="text-2xl font-bold mb-3">🌱 Recommendations</h2>
//             <p className="text-gray-600">
//               Receive AI-based suggestions tailored to your crops, soil, and seasonal conditions.
//             </p>
//           </div>

//         </div>
//       </main>

//       <Footer />
//     </div>
//   );
// }
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

export default function Dashboard() {
  return (
    <div className="min-h-screen flex flex-col bg-green-50">
      <Navbar />

      <main className="flex-1 px-6 py-10 max-w-7xl mx-auto w-full">

        {/* Welcome Banner */}
        <section className="bg-gradient-to-r from-green-700 to-green-500 rounded-3xl text-white p-8 shadow-xl">
          <h1 className="text-4xl font-bold">
            Welcome Back, Farmer 👋
          </h1>

          <p className="mt-3 text-lg">
            Here's your farm overview powered by AgriAI.
          </p>

          <button className="mt-6 bg-white text-green-700 px-6 py-3 rounded-xl font-semibold hover:scale-105 transition">
            Scan Crop Disease 🌾
          </button>
        </section>

        {/* Stats */}
        <section className="grid md:grid-cols-4 gap-6 mt-10">

          <div className="bg-white p-6 rounded-2xl shadow-lg">
            <p className="text-gray-500">Crop Health</p>
            <h2 className="text-4xl font-bold text-green-700 mt-2">
              92%
            </h2>
          </div>

          <div className="bg-white p-6 rounded-2xl shadow-lg">
            <p className="text-gray-500">Diseases Detected</p>
            <h2 className="text-4xl font-bold text-red-500 mt-2">
              18
            </h2>
          </div>

          <div className="bg-white p-6 rounded-2xl shadow-lg">
            <p className="text-gray-500">AI Recommendations</p>
            <h2 className="text-4xl font-bold text-blue-500 mt-2">
              24
            </h2>
          </div>

          <div className="bg-white p-6 rounded-2xl shadow-lg">
            <p className="text-gray-500">Notifications</p>
            <h2 className="text-4xl font-bold text-yellow-500 mt-2">
              5
            </h2>
          </div>

        </section>

        {/* Middle Section */}
        <section className="grid lg:grid-cols-3 gap-8 mt-10">

          {/* Recent Activity */}
          <div className="lg:col-span-2 bg-white rounded-2xl shadow-lg p-6">
            <h2 className="text-2xl font-bold text-green-700 mb-5">
              Recent AI Activity
            </h2>

            <div className="space-y-4">

              <div className="border-l-4 border-green-600 pl-4">
                <h3 className="font-semibold">
                  Tomato Leaf Analysis
                </h3>
                <p className="text-gray-600">
                  Early Blight detected with 94% confidence.
                </p>
              </div>

              <div className="border-l-4 border-yellow-500 pl-4">
                <h3 className="font-semibold">
                  Soil Recommendation
                </h3>
                <p className="text-gray-600">
                  Nitrogen level is low. Fertilizer suggested.
                </p>
              </div>

              <div className="border-l-4 border-blue-500 pl-4">
                <h3 className="font-semibold">
                  Weather Alert
                </h3>
                <p className="text-gray-600">
                  Heavy rainfall expected tomorrow.
                </p>
              </div>

            </div>
          </div>

          {/* Weather Widget */}
          <div className="bg-white rounded-2xl shadow-lg p-6">
            <h2 className="text-2xl font-bold text-green-700 mb-5">
              Today's Weather 🌤️
            </h2>

            <h3 className="text-5xl font-bold">28°C</h3>

            <p className="mt-3 text-gray-600">
              Dehradun, Uttarakhand
            </p>

            <div className="mt-6 space-y-2">
              <p>Humidity: 65%</p>
              <p>Wind: 12 km/h</p>
              <p>Rain Chance: 30%</p>
            </div>
          </div>

        </section>

        {/* Table */}
        <section className="bg-white rounded-2xl shadow-lg p-6 mt-10 overflow-x-auto">

          <h2 className="text-2xl font-bold text-green-700 mb-5">
            Recent Crop Scans
          </h2>

          <table className="w-full">

            <thead>
              <tr className="border-b">
                <th className="text-left py-3">Crop</th>
                <th className="text-left py-3">Disease</th>
                <th className="text-left py-3">Status</th>
                <th className="text-left py-3">Date</th>
              </tr>
            </thead>

            <tbody>

              <tr className="border-b">
                <td className="py-3">Tomato</td>
                <td>Early Blight</td>
                <td className="text-red-500">Detected</td>
                <td>21 Jun 2026</td>
              </tr>

              <tr className="border-b">
                <td className="py-3">Potato</td>
                <td>Healthy</td>
                <td className="text-green-600">Safe</td>
                <td>20 Jun 2026</td>
              </tr>

              <tr>
                <td className="py-3">Wheat</td>
                <td>Rust Disease</td>
                <td className="text-yellow-500">Moderate</td>
                <td>19 Jun 2026</td>
              </tr>

            </tbody>

          </table>

        </section>

      </main>

      <Footer />
    </div>
  );
}